/**
 * Server-issued identifiers.
 *
 * Both of these are deliberately generated by the SERVER: a client that picked its
 * own run id could replay one, and a client that picked its own seed could fish for
 * an easy layout and then submit the score as if it were a normal run.
 */
import { randomUUID, randomBytes } from 'node:crypto';

export function newRunId(): string {
  return randomUUID();
}

/** Unsigned 32-bit, matching the range the client's mulberry32 PRNG expects. */
export function newSeed(): number {
  return randomBytes(4).readUInt32BE(0);
}
