/**
 * Asset system — type definitions.
 *
 * DESIGN RULE (the most important one in this repository):
 *   Game code NEVER writes a file path. It refers to an *Asset ID* such as
 *   `late.player.run`, and the registry resolves that to a URL plus the metadata
 *   needed to load it. Replacing artwork therefore means editing ONE manifest entry
 *   (or overwriting the file it points at) and touching no gameplay code at all.
 */

export type AssetKind = 'image' | 'spritesheet' | 'audio';

/**
 * `placeholder` — temporary art generated by `npm run assets:placeholders`.
 * `final`       — real artwork delivered by the asset team.
 *
 * The dev asset browser (`/dev/assets`) and `docs/ASSETS.md` are both driven by
 * this flag, so the remaining work is always visible.
 */
export type AssetStatus = 'placeholder' | 'final';

export type AudioChannel = 'bgm' | 'se';

export interface Size {
  readonly width: number;
  readonly height: number;
}

interface AssetBase {
  readonly kind: AssetKind;
  /**
   * URL relative to the site root, always under `/assets/`.
   * Swapping artwork = change this string, or overwrite the file it points to.
   */
  readonly src: string;
  readonly status: AssetStatus;
  /** What this asset is used for, in Japanese, for whoever produces the real art. */
  readonly usage: string;
  /** Optional extra instructions shown in docs/ASSETS.md and /dev/assets. */
  readonly notes?: string;
}

export interface ImageAsset extends AssetBase {
  readonly kind: 'image';
  readonly recommendedSize: Size;
  /** Whether the final artwork must have an alpha channel. */
  readonly transparent: boolean;
}

export interface SpritesheetAsset extends AssetBase {
  readonly kind: 'spritesheet';
  /** Size of ONE frame. The file is `frameSize.width * frameCount` wide. */
  readonly frameSize: Size;
  readonly frameCount: number;
  /** Playback rate used when the registry builds the Phaser animation. */
  readonly frameRate: number;
  readonly loop: boolean;
  readonly transparent: boolean;
}

export interface AudioAsset extends AssetBase {
  readonly kind: 'audio';
  readonly channel: AudioChannel;
  readonly loop?: boolean;
  readonly approxDurationSec?: number;
}

export type AssetDefinition = ImageAsset | SpritesheetAsset | AudioAsset;

/** A manifest node is either an asset or a namespace of further nodes. */
export interface AssetGroup {
  readonly [key: string]: AssetDefinition | AssetGroup;
}

export function isAssetDefinition(node: AssetDefinition | AssetGroup): node is AssetDefinition {
  return typeof (node as AssetDefinition).kind === 'string';
}

/**
 * Recursively derives the dotted Asset ID union from the manifest shape, so a typo
 * like `getImage('late.player.runn')` is a compile error rather than a runtime
 * missing-texture.
 */
export type AssetPaths<T> = {
  [K in keyof T & string]: T[K] extends AssetDefinition
    ? K
    : T[K] extends object
      ? `${K}.${AssetPaths<T[K]>}`
      : never;
}[keyof T & string];

/** Bundles that can be loaded independently, so the first screen is cheap. */
export type AssetBundleId = 'common' | 'late' | 'bread' | 'teacher';

export interface ResolvedAsset {
  readonly id: string;
  readonly bundle: AssetBundleId;
  readonly definition: AssetDefinition;
}
